### ISSUE TITLE
请问有人用pyinstaller 生成可执行程序吗？遇到pycuda问题

### ISSUE THREAD

**Issue by wangliyjs** [cong/yolov5_deepsort_tensorrt#11]
[TensorRT] ERROR: /home/jenkins/workspace/TensorRT/helpers/rel-7.1/L1_Nightly_Internal/build/source/rtSafe/resources.h (460) - Cuda Error in loadKernel: 3 (initialization error)
[TensorRT] ERROR: INVALID_STATE: std::exception
[TensorRT] ERROR: INVALID_CONFIG: Deserialize the cuda engine failed.
Traceback (most recent call last):
  File "demo_trt.py", line 60, in <module>
  File "demo_trt.py", line 20, in detect
  File "detector_trt.py", line 86, in __init__
AttributeError: 'NoneType' object has no attribute 'create_execution_context'
[16873] Failed to execute script 'demo_trt' due to unhandled exception!
-------------------------------------------------------------------
PyCUDA ERROR: The context stack was not empty upon module cleanup.
-------------------------------------------------------------------
A context was still active when the context stack was being
cleaned up. At this point in our execution, CUDA may already
have been deinitialized, so there is no way we can finish
cleanly. The program will be aborted now.
Use Context.pop() to avoid this problem.
-------------------------------------------------------------------
已放弃 (核心已转储)

**Comment by StevenGerry** [comment]
Same problem

**Comment by Akhilesh1004** [comment]
我也有遇到相同的問題，一直無法解決
